name: turbo_responsiveness
description: Responsive design utilities and widgets for Flutter.
version: 1.0.0
homepage: https://github.com/appboypov/turbo_responsiveness
repository: https://github.com/appboypov/turbo_responsiveness

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  turbo_widgets: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
